apiVersion: skaffold/v2beta16
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    useDockerCLI: true
    push: false
  artifacts:
    - image: afif1400/orchestrator-service
      context: orchestrator
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: ./***/*.go
